### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by jannikpeters**
Updated to WS16/17

### CODE REVIEW

**Comment by Miroka96** [comment]
logic.js needs to be edited (currentSemester must be updated)

**Comment by knub** [comment]
Also, please double-check everything. There are typos `softwaremodlaritaet`, syntax errors (trailing comma in softwaremodlaritaet entry) and I think you mixed up knowledge discovery and knowledge mining.

**Comment by Miroka96** [comment]
I don't see how to branch from a pull request. Would be nice if somebody could merge the stuff

**Comment by Miroka96** [comment]
you can have a look at an actually running instance on http://www.codebase.one/180
argh, somehow it got broken...

**Comment by knub** [comment]
Miroko: Just fork @jannikpeters, make your changes and then make a pull-request against this repo again.

**Comment by knub** [comment]
Closing because of inactivity.

**Pull request closed without merging**
